version: '2'

volumes:
  downloads:
    external: true

services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    ports:
      # for access to the Plex Media Server [required]
      - "32400:32400"
      # for access to the Plex DLNA Server
      - "1900:1900/udp"
      - "32469:32469"
      # for current GDM network discovery
      # - "32410:32410/udp"
      # - "32412:32412/udp"
      # - "32413:32413/udp"
      # - "32414:32414/udp"
    volumes:
      - /home/bruce/plex-config:/config
      - /tmp:/transcode
      - downloads:/media
    environment:
      - TZ='Australia/Melbourne'
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    network_mode: host
