version: '2'

volumes:
  znc_data:
    external: true

services:
  znc:
    image: "znc:latest" 
    ports:
      - "33033:33033"
      # identserv
      - "113:11300"
    volumes:
      - znc_data:/znc-data
    restart: always
