version: '2'

volumes:
  znc_data:
    external: true

services:
  znc:
    image: "linuxserver/znc"
    ports:
      - "33033:33033"
      # identserv
      #- "113:11300"
    volumes:
      - znc_data:/config
    environment:
      - TZ=Australia/Melbourne
      - PGID=1000
      - PUID=1000
    restart: always
