version: '2'
volumes:
  downloads:
    external: true

services:
  transmission:
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413/tcp"  
      - "51413:51413/udp"  
      - "12345:12345/udp"
    volumes:
      - downloads:/downloads
      - /home/bruce/transmission-data:/config
    ulimits:
      core: 4096
    environment:
      - TZ='Australia/Melbourne'
      - PUID=1000
      - PGID=1000
    network_mode: host
    #restart: always
